---
- name: Install Python 2
  hosts: vm_002
  become: true
  gather_facts: False

  vars_files:
    - '../canadensys-inventories/cloud/vars_security_internal.yml'

  tasks:
  - name: install python 2
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

- name: Install Canadensys Community
  hosts: vm_002
  become: true

  vars_files:
    - '../canadensys-inventories/cloud/vars_common.yml'
    - '../canadensys-inventories/cloud/vars_security_internal.yml'
    - '../canadensys-inventories/cloud/vars_vm-002.yml'
  
  roles:
    - safe_upgrade
    - first_install
    - etc_hosts
    - firewall
    - nginx
    - mysql
    - php_fpm
    - fail2ban
    - fail2ban_nginx
    - log_watcher
    - nfs_client
    - wordpress_nginx_and_local_db

