---
# Nginx
- name: Nginx copy template from nginx to directory
  become: true
  template:
    src     : ./templates/nginx_to_directory.j2
    dest    : /etc/nginx/sites-available/{{ app_c_name }}

- name: Nginx activate website
  become: true
  file:
    src   : /etc/nginx/sites-available/{{ app_c_name }}
    dest  : /etc/nginx/sites-enabled/{{ app_c_name }}
    state : link
  notify: nginx reload

