---
- name: Update APT package cache
  become: true
  apt:
    pkg             : '{{ item }}'
    state           : present
    update_cache    : yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  with_items: '{{ update_pkgs }}'
    
- name: Upgrade APT to the latest packages
  become: true
  apt:
    upgrade: safe
