---
- name: Install Logwatch packages
  apt:
    pkg             : '{{ item }}'
    state           : present
    update_cache    : yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  with_items: '{{ logwatch_pkgs }}'

- name: Email log summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
              state=present create=yes
