# tomcat8 main variables
tomcat8:             tomcat8
tomcat8_user:        tomcat8
tomcat8_conf:        /etc/default/{{ tomcat8 }}
tomcat8_conf_dir:    /etc/{{ tomcat8 }}
tomcat8_conf_server: '{{ tomcat8_conf_dir }}/server.xml'
tomcat8_log_dir:     /var/log/{{ tomcat8 }}
tomcat8_dir:         /var/lib/{{ tomcat8 }}
#tomcat8_webapps:     /var/lib/webapps/

tomcat8_host_name:   tomcat8_host_name
tomcat8_maindir:     '/var/www/{{ tomcat8_host_name }}'
tomcat8_webapps:     '{{ tomcat8_maindir }}/webapps'


# tomcat8 specific variables
packaging: "war"
ufw_tomcat8_ports:
  - 8080
  
tomcat8_pkgs:
    - libtcnative-1
    - '{{ tomcat8 }}'

# Common tomcat8 variables across all roles
# replace option: -Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC
tomcat8_java_opts: -Xmx2g -Xms2g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
tomcat8_control_port: 8005
tomcat8_http: true
tomcat8_http_port: 8080
tomcat8_ajp: false
tomcat8_ajp_port: 8009
tomcat8_apr: true
tomcat8_users: true
tomcat8_autoDeploy: true
tomcat8_bind_addr: 0.0.0.0

