---
#- name: Change ssh port
#  lineinfile: dest=/etc/ssh/sshd_config
#              regexp="^Port\s"
#              line="Port {{ ssh_port }}"
#              state=present
#  notify: Restart ssh
    
- name: Disallow password authentication
  become: true
  lineinfile:
    dest    : '/etc/ssh/sshd_config'
    regexp  : "PasswordAuthentication"
    line    : "PasswordAuthentication no"
    state   : present
  notify: restart ssh

- name: Disallow root SSH access
  become: true
  lineinfile:
    dest    : /etc/ssh/sshd_config
    regexp  : "PermitRootLogin"
    line    : "PermitRootLogin no"
    state   : present
  notify: restart ssh

- name: Ensure ssh starts on a fresh reboot
  become: true
  service:
    name    : '{{ ssh }}'
    state   : started
    enabled : yes
