---
# Fail2ban packages
fail2ban_pkgs:
  - fail2ban

# Fail2ban variables
fail2ban_loglevel: 3
fail2ban_logtarget: /var/log/fail2ban.log
fail2ban_socket: /var/run/fail2ban/fail2ban.sock

fail2ban_ignoreip: 127.0.0.1/8 {{ ip_whitelist }}
fail2ban_bantime: 3600
fail2ban_maxretry: 6

fail2ban_backend: polling

fail2ban_destemail: root@localhost
fail2ban_banaction: iptables-multiport
fail2ban_mta: sendmail
fail2ban_protocol: tcp
fail2ban_chain: INPUT

fail2ban_action: action_

fail2ban_services:
  - name     : ssh
    port     : ssh
    banaction: ufw-ssh
    filter   : sshd
    logpath  : /var/log/auth.log
  - name     : apache-badbots
    enabled  : true
    port     : http,https
    filter   : apache-badbots
    logpath  : %(apache_access_log)s
    maxretry : 2
  - name     : apache-noscript
    enabled  : true
    port     : http,https
    logpath  : %(apache_error_log)s
    maxretry : 6
  - name     : apache-overflows
    enabled  : true
    port     : http,https
    filter   : apache-overflows
    logpath  : %(apache_error_log)s
    maxretry : 2
  - name     : apache-nohome
    enabled  : true
    port     : http,https
    filter   : apache-nohome
    logpath  : %(apache_error_log)s
    maxretry : 2
  - name    : apache
    enabled  : true
    port     : http,https
    filter   : apache-auth
    logpath  : /var/log/apache*/*error.log
    maxretry : 6
  - name    : php-url-fopen
    enabled : true
    port    : http,https
    filter  : php-url-fopen
    logpath : /var/log/apache*/*access.log

#ip_whitelist        : '10.241.64.0/24 192.168.56.0/24'
ip_whitelist        : '192.168.56.100/24'


