---
tomcat_user:        tomcat8
tomcat_webapps:     '{{ vascan_dir_root }}/webapps'

tmp_checkout_dir:    '/tmp/vascan/checkout'

google_analytics:
  site_verification:
  account:

# Attributes related to sources (on GitHub)
source_dict:
  data_access:
    repo: https://github.com/Canadensys/canadensys-data-access.git
    checkout_dir: '{{ tmp_checkout_dir }}/canadensys-data-access'
    version: '2.15.0'
  vascan:
    repo: https://github.com/Canadensys/vascan.git
    checkout_dir: '{{ tmp_checkout_dir }}/vascan'
    version: 'dev'

# Last release version. Mostly use to versionned web assets (e.g. css and js)
vascan_version: '3.5.4'

elastic_search:
  host: 127.0.0.1
  port: 9200
  create_index: '{{ source_dict.data_access.checkout_dir }}/src/main/resources/script/vascan/vascan_index_creation.txt'

# used by the ElasticSearch role
vascan_elasticsearch_plugins: 
  - name: jdbc-river
    url: http://bit.ly/1a8Mcve
    dir: jdbc

mysql_java_connector_version: mysql-connector-java-5.1.31
mysql_java_connector_url: 'https://dev.mysql.com/get/Downloads/Connector-J/{{ mysql_java_connector_version }}.zip'
mysql_java_connector_jar: '{{ mysql_java_connector_version }}-bin.jar'

elastic_search_rivers:
  taxon:
    type: taxon
    sql: SELECT l1.taxonid as _id,l1.calname as taxonname,l1.calname as sortname,l1.calnamehtml as namehtml, l1.calnamehtmlauthor as namehtmlauthor, l1.status,parentid,l2.calnamehtml AS parentnamehtml, l1.rank as rankname FROM lookup l1  LEFT OUTER JOIN taxonomy on childid = taxonid LEFT OUTER JOIN lookup as l2 on l2.taxonid = parentid
  vernacular:
    type: vernacular
    sql: SELECT v.id AS _id, v.taxonid ,name as vernacularname,name as sortname,s.status,language,calnamehtml AS taxonnamehtml FROM vernacularname v INNER JOIN status s on statusid = s.id INNER JOIN lookup on lookup.taxonid=v.taxonid

vascan_apps_dir:
  generated_images:   '{{ vascan_dir.data }}/generated_img/'
  generated_content:  '{{ vascan_dir.generated_content }}'

db_dict:
  prod:
    db_name: vascan_newprod
    db_user: wwwuser
    db_password: my_password
    db_host: localhost
    db_src: '../templates/mysqldump_vascan_newprod.gz'
    db_dest: '/tmp'
    db_zip: /tmp/mysqldump_vascan_newprod.gz

