---
- name: restart ssh
  become: true
  service:
    name    : '{{ ssh }}'
    state   : restarted

- name: restart iptables
  become: true
  service: name=iptables enabled=yes state=restarted

- name: reload iptables
  become: true
  shell: iptables-restore <  /etc/sysconfig/iptables

- name: restart ufw
  become: true
  service:
    name    : '{{ ufw }}'
    state   : restarted
