- name: restart tomcat
  become: true
  service:
    name    : '{{ tomcat }}'
    state   : restarted

- name: restart mysql
  become: true
  service:
    name    : '{{ mysql }}'
    state   : restarted
