nginx_sites:
  vascan:
      - listen 80
      - server_name localhost
      - root "/tmp/html"
      - 'location /vascan-editor { 
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://localhost:8080/vascan-editor/;
        }'
      - 'location /vascan { 
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://localhost:8080/vascan/; 
        }'
      - 'location /tools { 
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://localhost:8080/tools/;
        }'
     