---
- name: Install Mediawiki packages
  become: true
  apt:
    pkg             : '{{ item }}'
    state           : present
    update_cache    : yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  with_items: '{{ mediawiki_pkgs }}'
