---
- name: install tomcat7
  become: true
  apt:
    pkg             : '{{ item }}'
    state           : present
    update_cache    : yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  with_items: '{{ tomcat7_pkgs }}'

- name: enable the AJP 1.3 connector
  become: true
  tomcat_connector: name="AJP/1.3"
  notify:
    - restart tomcat

- name: configure tomcat memory
  become: true
  lineinfile: 
    dest={{ tomcat7_conf }}
    regexp="^JAVA_OPTS"
    line='JAVA_OPTS="{{ tomcat7_java_opts }}"'
  notify: 
    - restart tomcat

- name: Set JAVA_HOME Tomcat7 and java-7-oracle
  become: true
  lineinfile: 
    dest={{ tomcat7_conf }}
    regexp="JAVA_HOME"
    line='JAVA_HOME={{ java_home_path }}'
  notify: 
    - restart tomcat

- name: Change the default tomcat web page directory Tomcat7
  become: true
  replace: 
    dest={{ tomcat7_conf_server }}
    regexp='<Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">'
    replace='<Host name="localhost" appBase="{{ tomcat7_webapps }}" unpackWARs="true" autoDeploy="true">'
  notify: 
    - restart tomcat

- name: ufw - Allow tomcat traffic
  become: true
  ufw: rule=allow port={{ item }} proto=tcp
  with_items: "{{ ufw_tomcat7_ports }}"

- name: Ensure tomcat7 starts on a fresh reboot
  become: true
  service:
    name    : '{{ tomcat7 }}'
    state   : started
    enabled : yes
