---
# Fail2ban packages
fail2ban_pkgs:
  - fail2ban

# Fail2ban variables
fail2ban_loglevel: 3
fail2ban_logtarget: /var/log/fail2ban.log
fail2ban_socket: /var/run/fail2ban/fail2ban.sock

fail2ban_ignoreip: 127.0.0.1/8 {{ ip_whitelist }}
fail2ban_bantime: 3600
fail2ban_maxretry: 6

fail2ban_backend: polling

fail2ban_destemail: '{{ canadensys_email }}'
fail2ban_banaction: iptables-multiport
fail2ban_mta: sendmail
fail2ban_protocol: tcp
fail2ban_chain: INPUT

fail2ban_action: action_

fail2ban_services:
  - name     : ssh
    port     : ssh
    banaction: ufw-ssh
    filter   : sshd
    logpath  : /var/log/auth.log

ip_whitelist        : ''
